--
-- PostgreSQL database dump
--

\restrict t5bJ3G3DDsaPtYLFSJUjWwxFYekPlORn7O6n3s5MzhjkmLUTO1CPiNc2OyvZFLG

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_conocimientotema; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_conocimientotema (
    id bigint NOT NULL,
    nivel_conocimiento numeric(5,4) NOT NULL,
    respuestas_totales integer NOT NULL,
    respuestas_correctas integer NOT NULL,
    ultima_actualizacion timestamp with time zone NOT NULL,
    tema_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT core_conocimientotema_respuestas_correctas_check CHECK ((respuestas_correctas >= 0)),
    CONSTRAINT core_conocimientotema_respuestas_totales_check CHECK ((respuestas_totales >= 0))
);


--
-- Name: core_conocimientotema_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_conocimientotema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_conocimientotema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_conversacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_conversacion (
    id bigint NOT NULL,
    titulo character varying(200) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    activa boolean NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: core_conversacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_conversacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_conversacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_documento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_documento (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    archivo character varying(100) NOT NULL,
    fecha_subida timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    tema_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: core_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_documento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_ejercicio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_ejercicio (
    id bigint NOT NULL,
    titulo character varying(200) NOT NULL,
    instrucciones text NOT NULL,
    dificultad character varying(20) NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    tema_id bigint NOT NULL
);


--
-- Name: core_ejercicio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_ejercicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_ejercicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_intento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_intento (
    id bigint NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone,
    calificacion numeric(5,2),
    completado boolean NOT NULL,
    ejercicio_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


--
-- Name: core_intento_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_intento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_intento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_materia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_materia (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    activo boolean NOT NULL
);


--
-- Name: core_materia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_materia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_materia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_mensaje; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_mensaje (
    id bigint NOT NULL,
    tipo character varying(10) NOT NULL,
    contenido text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    conversacion_id bigint NOT NULL
);


--
-- Name: core_mensaje_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_mensaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_mensaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_pregunta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_pregunta (
    id bigint NOT NULL,
    texto text NOT NULL,
    opcion_a character varying(255) NOT NULL,
    opcion_b character varying(255) NOT NULL,
    opcion_c character varying(255) NOT NULL,
    opcion_d character varying(255) NOT NULL,
    respuesta_correcta character varying(1) NOT NULL,
    explicacion text NOT NULL,
    ejercicio_id bigint NOT NULL
);


--
-- Name: core_pregunta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_pregunta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_pregunta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_progreso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_progreso (
    id bigint NOT NULL,
    porcentaje numeric(5,2) NOT NULL,
    ejercicios_completados integer NOT NULL,
    ejercicios_correctos integer NOT NULL,
    ultima_actividad timestamp with time zone NOT NULL,
    tema_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT core_progreso_ejercicios_completados_check CHECK ((ejercicios_completados >= 0)),
    CONSTRAINT core_progreso_ejercicios_correctos_check CHECK ((ejercicios_correctos >= 0))
);


--
-- Name: core_progreso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_progreso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_progreso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_recomendacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_recomendacion (
    id bigint NOT NULL,
    titulo character varying(200) NOT NULL,
    descripcion text NOT NULL,
    tipo character varying(30) NOT NULL,
    prioridad integer NOT NULL,
    atendida boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    tema_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT core_recomendacion_prioridad_check CHECK ((prioridad >= 0))
);


--
-- Name: core_recomendacion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_recomendacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_recomendacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_respuesta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_respuesta (
    id bigint NOT NULL,
    respuesta_usuario character varying(1) NOT NULL,
    es_correcta boolean NOT NULL,
    fecha_respuesta timestamp with time zone NOT NULL,
    intento_id bigint NOT NULL,
    pregunta_id bigint NOT NULL
);


--
-- Name: core_respuesta_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_respuesta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_respuesta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_tema; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_tema (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    numero integer NOT NULL,
    unidad_id bigint NOT NULL,
    CONSTRAINT core_tema_numero_check CHECK ((numero >= 0))
);


--
-- Name: core_tema_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_tema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_tema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_unidad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_unidad (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text NOT NULL,
    numero integer NOT NULL,
    materia_id bigint NOT NULL,
    CONSTRAINT core_unidad_numero_check CHECK ((numero >= 0))
);


--
-- Name: core_unidad_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_unidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_unidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_usuario (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    correo character varying(254) NOT NULL,
    password character varying(255) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    activo boolean NOT NULL,
    rol character varying(20) NOT NULL
);


--
-- Name: core_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_conocimientotema core_conocimientotema_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_conocimientotema
    ADD CONSTRAINT core_conocimientotema_pkey PRIMARY KEY (id);


--
-- Name: core_conversacion core_conversacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_conversacion
    ADD CONSTRAINT core_conversacion_pkey PRIMARY KEY (id);


--
-- Name: core_documento core_documento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_documento
    ADD CONSTRAINT core_documento_pkey PRIMARY KEY (id);


--
-- Name: core_ejercicio core_ejercicio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_ejercicio
    ADD CONSTRAINT core_ejercicio_pkey PRIMARY KEY (id);


--
-- Name: core_intento core_intento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_intento
    ADD CONSTRAINT core_intento_pkey PRIMARY KEY (id);


--
-- Name: core_materia core_materia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_materia
    ADD CONSTRAINT core_materia_pkey PRIMARY KEY (id);


--
-- Name: core_mensaje core_mensaje_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_mensaje
    ADD CONSTRAINT core_mensaje_pkey PRIMARY KEY (id);


--
-- Name: core_pregunta core_pregunta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_pregunta
    ADD CONSTRAINT core_pregunta_pkey PRIMARY KEY (id);


--
-- Name: core_progreso core_progreso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_progreso
    ADD CONSTRAINT core_progreso_pkey PRIMARY KEY (id);


--
-- Name: core_recomendacion core_recomendacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_recomendacion
    ADD CONSTRAINT core_recomendacion_pkey PRIMARY KEY (id);


--
-- Name: core_respuesta core_respuesta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_respuesta
    ADD CONSTRAINT core_respuesta_pkey PRIMARY KEY (id);


--
-- Name: core_tema core_tema_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_tema
    ADD CONSTRAINT core_tema_pkey PRIMARY KEY (id);


--
-- Name: core_unidad core_unidad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_unidad
    ADD CONSTRAINT core_unidad_pkey PRIMARY KEY (id);


--
-- Name: core_usuario core_usuario_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usuario
    ADD CONSTRAINT core_usuario_correo_key UNIQUE (correo);


--
-- Name: core_usuario core_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_usuario
    ADD CONSTRAINT core_usuario_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_conocimientotema_tema_id_17cf763e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_conocimientotema_tema_id_17cf763e ON public.core_conocimientotema USING btree (tema_id);


--
-- Name: core_conocimientotema_usuario_id_4f3ca645; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_conocimientotema_usuario_id_4f3ca645 ON public.core_conocimientotema USING btree (usuario_id);


--
-- Name: core_conversacion_usuario_id_1cce886c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_conversacion_usuario_id_1cce886c ON public.core_conversacion USING btree (usuario_id);


--
-- Name: core_documento_tema_id_b58d2d1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_documento_tema_id_b58d2d1b ON public.core_documento USING btree (tema_id);


--
-- Name: core_documento_usuario_id_9423b44d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_documento_usuario_id_9423b44d ON public.core_documento USING btree (usuario_id);


--
-- Name: core_ejercicio_tema_id_68b25a13; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_ejercicio_tema_id_68b25a13 ON public.core_ejercicio USING btree (tema_id);


--
-- Name: core_intento_ejercicio_id_f594dca6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_intento_ejercicio_id_f594dca6 ON public.core_intento USING btree (ejercicio_id);


--
-- Name: core_intento_usuario_id_1a63598b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_intento_usuario_id_1a63598b ON public.core_intento USING btree (usuario_id);


--
-- Name: core_mensaje_conversacion_id_d56f24f0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_mensaje_conversacion_id_d56f24f0 ON public.core_mensaje USING btree (conversacion_id);


--
-- Name: core_pregunta_ejercicio_id_d942e413; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_pregunta_ejercicio_id_d942e413 ON public.core_pregunta USING btree (ejercicio_id);


--
-- Name: core_progreso_tema_id_b5eee022; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_progreso_tema_id_b5eee022 ON public.core_progreso USING btree (tema_id);


--
-- Name: core_progreso_usuario_id_27d98043; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_progreso_usuario_id_27d98043 ON public.core_progreso USING btree (usuario_id);


--
-- Name: core_recomendacion_tema_id_3a8f086d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_recomendacion_tema_id_3a8f086d ON public.core_recomendacion USING btree (tema_id);


--
-- Name: core_recomendacion_usuario_id_f0510228; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_recomendacion_usuario_id_f0510228 ON public.core_recomendacion USING btree (usuario_id);


--
-- Name: core_respuesta_intento_id_f00aceba; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_respuesta_intento_id_f00aceba ON public.core_respuesta USING btree (intento_id);


--
-- Name: core_respuesta_pregunta_id_3380b052; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_respuesta_pregunta_id_3380b052 ON public.core_respuesta USING btree (pregunta_id);


--
-- Name: core_tema_unidad_id_a4f6333b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_tema_unidad_id_a4f6333b ON public.core_tema USING btree (unidad_id);


--
-- Name: core_unidad_materia_id_b2d09e70; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_unidad_materia_id_b2d09e70 ON public.core_unidad USING btree (materia_id);


--
-- Name: core_usuario_correo_1000405d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_usuario_correo_1000405d_like ON public.core_usuario USING btree (correo varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_conocimientotema core_conocimientotema_tema_id_17cf763e_fk_core_tema_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_conocimientotema
    ADD CONSTRAINT core_conocimientotema_tema_id_17cf763e_fk_core_tema_id FOREIGN KEY (tema_id) REFERENCES public.core_tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_conocimientotema core_conocimientotema_usuario_id_4f3ca645_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_conocimientotema
    ADD CONSTRAINT core_conocimientotema_usuario_id_4f3ca645_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_conversacion core_conversacion_usuario_id_1cce886c_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_conversacion
    ADD CONSTRAINT core_conversacion_usuario_id_1cce886c_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_documento core_documento_tema_id_b58d2d1b_fk_core_tema_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_documento
    ADD CONSTRAINT core_documento_tema_id_b58d2d1b_fk_core_tema_id FOREIGN KEY (tema_id) REFERENCES public.core_tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_documento core_documento_usuario_id_9423b44d_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_documento
    ADD CONSTRAINT core_documento_usuario_id_9423b44d_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_ejercicio core_ejercicio_tema_id_68b25a13_fk_core_tema_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_ejercicio
    ADD CONSTRAINT core_ejercicio_tema_id_68b25a13_fk_core_tema_id FOREIGN KEY (tema_id) REFERENCES public.core_tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_intento core_intento_ejercicio_id_f594dca6_fk_core_ejercicio_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_intento
    ADD CONSTRAINT core_intento_ejercicio_id_f594dca6_fk_core_ejercicio_id FOREIGN KEY (ejercicio_id) REFERENCES public.core_ejercicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_intento core_intento_usuario_id_1a63598b_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_intento
    ADD CONSTRAINT core_intento_usuario_id_1a63598b_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_mensaje core_mensaje_conversacion_id_d56f24f0_fk_core_conversacion_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_mensaje
    ADD CONSTRAINT core_mensaje_conversacion_id_d56f24f0_fk_core_conversacion_id FOREIGN KEY (conversacion_id) REFERENCES public.core_conversacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_pregunta core_pregunta_ejercicio_id_d942e413_fk_core_ejercicio_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_pregunta
    ADD CONSTRAINT core_pregunta_ejercicio_id_d942e413_fk_core_ejercicio_id FOREIGN KEY (ejercicio_id) REFERENCES public.core_ejercicio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_progreso core_progreso_tema_id_b5eee022_fk_core_tema_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_progreso
    ADD CONSTRAINT core_progreso_tema_id_b5eee022_fk_core_tema_id FOREIGN KEY (tema_id) REFERENCES public.core_tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_progreso core_progreso_usuario_id_27d98043_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_progreso
    ADD CONSTRAINT core_progreso_usuario_id_27d98043_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_recomendacion core_recomendacion_tema_id_3a8f086d_fk_core_tema_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_recomendacion
    ADD CONSTRAINT core_recomendacion_tema_id_3a8f086d_fk_core_tema_id FOREIGN KEY (tema_id) REFERENCES public.core_tema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_recomendacion core_recomendacion_usuario_id_f0510228_fk_core_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_recomendacion
    ADD CONSTRAINT core_recomendacion_usuario_id_f0510228_fk_core_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.core_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_respuesta core_respuesta_intento_id_f00aceba_fk_core_intento_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_respuesta
    ADD CONSTRAINT core_respuesta_intento_id_f00aceba_fk_core_intento_id FOREIGN KEY (intento_id) REFERENCES public.core_intento(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_respuesta core_respuesta_pregunta_id_3380b052_fk_core_pregunta_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_respuesta
    ADD CONSTRAINT core_respuesta_pregunta_id_3380b052_fk_core_pregunta_id FOREIGN KEY (pregunta_id) REFERENCES public.core_pregunta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_tema core_tema_unidad_id_a4f6333b_fk_core_unidad_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_tema
    ADD CONSTRAINT core_tema_unidad_id_a4f6333b_fk_core_unidad_id FOREIGN KEY (unidad_id) REFERENCES public.core_unidad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_unidad core_unidad_materia_id_b2d09e70_fk_core_materia_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_unidad
    ADD CONSTRAINT core_unidad_materia_id_b2d09e70_fk_core_materia_id FOREIGN KEY (materia_id) REFERENCES public.core_materia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict t5bJ3G3DDsaPtYLFSJUjWwxFYekPlORn7O6n3s5MzhjkmLUTO1CPiNc2OyvZFLG

